version: '3.5'
services:
  gql-portal-redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - graphql-portal

  gql-portal-mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - graphql-portal

  gql-portal-dashboard:
    image: gqlportal/dashboard
    depends_on:
      - gql-portal-redis
      - gql-portal-mongo
    ports:
      - 3030:3030
    networks:
      - graphql-portal
    environment:
      - REDIS_CONNECTION_STRING=redis://gql-portal-redis:6379
      - MONGODB_CONNECTION_STRING=mongodb://gql-portal-mongo:27017/graphql-portal-dashboard
      - DASHBOARD_PORT=3030
      - DASHBOARD_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJnYXRld2F5Iiwicm9sZSI6ImdhdGV3YXkiLCJpYXQiOjE2MTM1ODMxNzR9.dIf32qZjvPATeT35ZxXbJYkN6jDL81qVilx69-GvI10
      - DEFAULT_ADMIN_EMAIL=admin@example.com
      - DEFAULT_ADMIN_PASSWORD=Secret123!
      - GRAPHQL_PLAYGROUND=true
      - SERVE_STATIC=true

  gql-portal-gateway:
    image: gqlportal/gateway
    depends_on:
      - gql-portal-redis
      - gql-portal-dashboard
    ports:
      - "3000:3000"
    networks:
      - graphql-portal
    volumes:
      - ./config-examples/with-dashboard:/opt/graphql-portal/config/
    environment:
      - REDIS_CONNECTION_STRING=redis://gql-portal-redis:6379
      - DASHBOARD_CONNECTION_STRING=http://gql-portal-dashboard:3030
    command:
      - "/bin/sh"
      - "-c"
      - "echo 'Waiting for 5 seconds for Dashboard to come online...' && /bin/sleep 5 && cd /opt/graphql-portal && graphql-portal"

volumes:
  redis-data:
  mongo-data:

networks:
  graphql-portal:
